// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListDirectories(arg1, arg2) {
  return window['go']['main']['App']['ListDirectories'](arg1, arg2);
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function ListMachines() {
  return window['go']['main']['App']['ListMachines']();
}

export function RunJobNow(arg1) {
  return window['go']['main']['App']['RunJobNow'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['main']['App']['SaveJob'](arg1);
}

export function SelectPath(arg1, arg2) {
  return window['go']['main']['App']['SelectPath'](arg1, arg2);
}
