// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteJob(arg1:string):Promise<void>;

export function GetLogs(arg1:string):Promise<Array<main.LogEntry>>;

export function GetStatus():Promise<main.Status>;

export function ListDirectories(arg1:string,arg2:string):Promise<Array<main.DirectoryEntry>>;

export function ListJobs():Promise<Array<main.SyncJob>>;

export function ListMachines():Promise<Array<main.Machine>>;

export function RunJobNow(arg1:string):Promise<void>;

export function SaveJob(arg1:main.SyncJob):Promise<main.SyncJob>;

export function SelectPath(arg1:string,arg2:string):Promise<string>;
